import {StyleSheet} from 'react-native';
import {Colors} from 'react-native/Libraries/NewAppScreen';

const backColor = '#1f1a17';
const utfYellow = '#ffcc00';

export const styles = StyleSheet.create({
  mainLogo: {
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: '30%',
    marginBottom: '20%',
    width: 250,
    height: 50,
  },
  mainText: {
    fontSize: 17,
    fontWeight: 'bold',
    marginTop: '10%',
  },
  footerText: {
    color: Colors.light,
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: '20%',
  },
  sectionContainer: {
    alignItems: 'center',
    marginTop: 32,
    paddingHorizontal: 24,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
  },
  sectionDescription: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: '400',
  },
  highlight: {
    fontWeight: '700',
  },
  input: {
    color: Colors.white,
    margin: 12,
    borderColor: utfYellow,
    marginLeft: 50,
    marginRight: 50,
    borderRadius: 50,
    borderWidth: 2,
    paddingHorizontal: 40,
  },
  backgroundStyle: {
    backgroundColor: backColor,
    height: '100%',
  },
  editTask: {
    backgroundColor: backColor,
  },
  container: {},
  header: {
    fontSize: 20,
  },
  nav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  navItem: {
    flex: 1,
    alignItems: 'center',
    padding: 10,
    backgroundColor: '#fff',
  },
  subNavItem: {
    padding: 5,
  },
  topic: {
    textAlign: 'center',
    fontSize: 15,
  },
  taskBackground: {
    backgroundColor: '#2C2C2C',
    borderRadius: 50,
    margin: 10,
    padding: 10,
    marginVertical: 1,
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  taskText: {
    color: '#fff',
    marginRight: 10,
  },
  taskMenu: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 60,
    height: 30,
    backgroundColor: utfYellow,
    borderRadius: 50,
    marginLeft: 15,
    marginRight: 15,
    marginTop: 10,
  },
  filterMenu: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 100,
    height: 30,
    backgroundColor: '#4D4D4D',
    borderRadius: 50,
    marginLeft: 15,
    marginRight: 15,
    marginTop: 10,
  },
  title: {
    color: '#ffffff',
    marginLeft: 10,
    fontSize: 16,
  },
  button: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 20,
    height: 20,
    marginRight: 10,
    backgroundColor: utfYellow,
    borderRadius: 50,
  },
  buttonDisabled: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 20,
    height: 20,
    marginRight: 10,
    backgroundColor: '#626262',
    borderRadius: 50,
  },
  deleteButton: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 20,
    height: 20,
    marginRight: 10,
    backgroundColor: '#626262',
    borderRadius: 50,
  },
  highPriority: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 20,
    height: 20,
    marginRight: 10,
    backgroundColor: '#E10947',
    borderRadius: 50,
  },
  mediumPriority: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 20,
    height: 20,
    marginRight: 10,
    backgroundColor: '#09E144',
    borderRadius: 50,
  },
  lowPriority: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 20,
    height: 20,
    marginRight: 10,
    backgroundColor: '#09E1CD',
    borderRadius: 50,
  },
  loginButton: {
    alignItems: 'center',
    backgroundColor: utfYellow,
    padding: 10,
    width: 140,
    borderRadius: 50,
    marginTop: 10,
    marginBottom: 10,
    marginRight: 14,
  },
  registerButton: {
    borderWidth: 1,
    borderColor: utfYellow,
    alignItems: 'center',
    backgroundColor: backColor,
    padding: 10,
    width: 140,
    borderRadius: 50,
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 14,
  },
  outlinedButton: {
    borderWidth: 1,
    borderColor: utfYellow,
    alignItems: 'center',
    backgroundColor: backColor,
    padding: 10,
    width: 100,
    borderRadius: 50,
  },
  standardButton: {
    borderWidth: 1,
    borderColor: '#fff',
    alignItems: 'center',
    backgroundColor: backColor,
    padding: 10,
    borderRadius: 50,
    width: 140,
    marginTop: 4,
    marginBottom: 10,
  },
  containedButton: {
    borderWidth: 1,
    borderColor: '#fff',
    alignItems: 'center',
    backgroundColor: backColor,
    padding: 10,
    borderRadius: 50,
    width: 140,
    marginTop: 4,
    marginBottom: 10,
  },
  horizontalAlign: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  horizontalAlignSpaceBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  horizontalAlignSpaceAround: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    padding: 20,
  },
});
